#!/bin/sh
dte(){
        dte="$(date +"%a, %b %d %R")"
        echo "$dte"
}

hdd(){
        hdd="$(df -h /home | grep dev | awk '{print$3, " "  $5}')"
        echo "HDD: $hdd"
}

mem(){
        mem="$(free -h | awk '/Mem:/ {printf $3 " / " $2}')"
        echo "Mem: $mem"
}
vol(){
	vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4":"$2}')"
	echo "Volume $vol"
}
mic(){
	mic="$(amixer -D pulse get Capture | awk -F'[][]' 'END{print $4":"$2}')"
	echo "MIC $mic"

}

kernel(){
	kernel="$(uname -sr | sed "s/-amd64//g")"
	echo $kernel
}



bat() {
	battery="$(cat /sys/class/power_supply/BAT0/capacity)"
	echo "$battery %"
}

batstat() {
	bstat="$(cat /sys/class/power_supply/BAT0/status)"
	echo "$bstat"
}

status(){
	echo "$(batstat) | $(bat) | $(kernel)| $(hdd) | $(mem) | $(vol) | $(mic) | $(dte)"
}


while true; do
	xsetroot -name "$(status)"
	sleep 10
done
